### ISSUE TITLE
All responses are null

### ISSUE THREAD

**Issue by gusen180** [betfair/API-NG-sample-code#18]
Have anything changed during the summer?
None of my projects from jun are getting any data back from the service. (Response come back null)

I even tested with the sample code without any modifications and still get stuck at "listEventTypes".

Exception: Object reference not set to an instance of an object.

(I have changed my sessionsToken ofc, tested with both delayed and normal)

**Comment by doowad** [comment]
Hi, 
Please email bdp@betfair.com.

Thanks

**Comment by rjft197** [comment]
For anyone interested.  I had the same problem and the response I got back pointed me to

https://api.developer.betfair.com/services/webapps/docs/display/1smk3cen4v3lu3yomq5qye0ni/27th+July+2015+-+Betfair+API+-+Withdrawal+of+Support+for+Expect%3A+100+Continue

All you need to do is add
          System.Net.ServicePointManager.Expect100Continue = false;

to your code and it will work.  I think it may be worth adding that direct into the sample code app
