### ISSUE TITLE
Noninteractive login sample not work

### ISSUE THREAD

**Issue by piao217** [betfair/API-NG-sample-code#33]
Hi
I have been struggling to achieve Noninteractive login to Betfair.
I'm using C# and on Windows 10.
- I have app key
- I created certificates with no password following the url:
https://www.youtube.com/watch?v=8N-EnnmN59Y&t=51s
- I uploaded the *.crt to my account and it's like:
![2018-12-03_04h01_34](https://user-images.githubusercontent.com/34410700/49344302-334a8980-f6b0-11e8-8761-063390941d72.png)
![2018-12-03_04h08_02](https://user-images.githubusercontent.com/34410700/49344371-09de2d80-f6b1-11e8-9dfb-54610371bd1b.png)

- Now according to the note from the sample, I created *.pfx for P12.

So I think everything is done in right order but it keeps saying internal error.
![2018-12-03_04h05_33](https://user-images.githubusercontent.com/34410700/49344344-d3a0ae00-f6b0-11e8-88ee-59080753dc59.png)

Could anyone help me?

**Comment by Asura5** [comment]
Wang

What endpoint are you using?

Dave

**Comment by piao217** [comment]
Hi, Asura5. Thanks for your help.
I tried both of old and new endpoints.
https://identitysso.betfair.com/api/certlogin
https://identitysso-cert.betfair.com/api/certlogin

But no luck.

**Comment by piao217** [comment]
I can share my username, cert key and app key for reproduction.

**Comment by newmanifold** [comment]
I've tried login using CURL and openssl it's working .
endpoint: 'https://identitysso-cert.betfair.com/api/certlogin

**Comment by piao217** [comment]
Oh, sorry.
I was misunderstanding the flow.
When it asks password, I thought it was the password for certificate.
Now I use the password for the account and it works.
Sorry for raising stupid issues.
Sorry to everyone who spent time because of my fault.
